### ISSUE TITLE
App crashes when it is launched first time without Internet

### ISSUE THREAD

**Issue by egornemov** [meugen/popularmovies#1]
08-28 14:54:13.049 11211 11233 D OkHttp  : --> GET https://api.themoviedb.org/3/movie/popular?api_key=4d0aefea62c601c18d2e9902f2570a61 http/1.1
08-28 14:54:13.049 11211 11233 D OkHttp  : --> END GET
08-28 14:54:13.050   346  7385 I SurfaceFlinger: EventThread Client Pid (11211) created
08-28 14:54:13.051 11211 11233 I System.out: [CDS][DNS] getAllByNameImpl netId = 0
08-28 14:54:13.051 11211 11211 D WindowClient: Add to mViews: com.android.internal.policy.PhoneWindow$DecorView{a74bde2 I.E...... R.....ID 0,0-0,0}, this = android.view.WindowManagerGlobal@9cd6477
08-28 14:54:13.051 11211 11233 D libc-netbsd: [getaddrinfo]: mtk hostname=api.themoviedb.org; servname=(null); netid=0; mark=0
08-28 14:54:13.051 11211 11233 D libc-netbsd: getaddrinfo( app_uid:10172
08-28 14:54:13.051 11211 11233 D libc-netbsd: getaddrinfo() uid prop:
08-28 14:54:13.051 11211 11233 D libc-netbsd: getaddrinfo() getuid():10172
08-28 14:54:13.051 11211 11233 D libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-28 14:54:13.052 11211 11233 D libc-netbsd: [getaddrinfo]: mtk hostname=api.themoviedb.org; servname=(null); netid=0; mark=0
08-28 14:54:13.052 11211 11233 D libc-netbsd: getaddrinfo( app_uid:10172
08-28 14:54:13.052 11211 11233 D libc-netbsd: getaddrinfo() uid prop:
08-28 14:54:13.052 11211 11233 D libc-netbsd: getaddrinfo() getuid():10172
08-28 14:54:13.052 11211 11233 D libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
08-28 14:54:13.052   482  1131 D FrameworkListener: dispatchCommand data = (getaddrinfo api.themoviedb.org ^ 1024 0 1 0 0)
08-28 14:54:13.052 11211 11211 D OpenGLRenderer: Dumper init 5 threads <0x7f9d117e80>
08-28 14:54:13.052 11211 11211 D OpenGLRenderer: <ua.meugen.android.popularmovies> is running.
08-28 14:54:13.053   482 11234 D libc-netbsd: [getaddrinfo]: mtk hostname=api.themoviedb.org; servname=(null); netid=0; mark=0
08-28 14:54:13.053   482 11234 D libc-netbsd: getaddrinfo( app_uid:0
08-28 14:54:13.053   482 11234 D libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
08-28 14:54:13.053   482 11234 D libc-netbsd: getaddrinfo: api.themoviedb.org get result from proxy gai_error = 11
08-28 14:54:13.053   482 11234 D libc-netbsd: default dns: query_ipv6=0, query_ipv4=0
08-28 14:54:13.053 11211 11233 D libc-netbsd: getaddrinfo: api.themoviedb.org get result from proxy gai_error = 7
08-28 14:54:13.054 11211 11233 I System.out: [CDS][DNS]Unable to resolve host "api.themoviedb.org": No address associated with hostname
08-28 14:54:13.054   346  2965 I SurfaceFlinger: EventThread Client Pid (11211) created
08-28 14:54:13.054 11211 11233 D OkHttp  : <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "api.themoviedb.org": No address associated with hostname
08-28 14:54:13.055 11211 11235 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-28 14:54:13.055 11211 11235 D OpenGLRenderer: CanvasContext() 0x7f9d1b2800
08-28 14:54:13.062 10928 10935 I System  : FinalizerDaemon: finalize objects = 70
08-28 14:54:13.064 11211 11211 I [MALI][Gralloc]: [+]r_hnd(0x7f97948f00), client(42), share_fd(40)
08-28 14:54:13.064 11211 11211 D GraphicBuffer: register, handle(0x7f97948f00) (w:1856 h:2048 s:1856 f:0x1 u:0x000100)
08-28 14:54:13.065 11211 11211 D ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{c1a38e4 ua.meugen.android.popularmovies/ua.meugen.android.popularmovies.ui.activities.MoviesActivity,ident = 0}
08-28 14:54:13.066   346  2965 I SurfaceFlinger: [SF client] NEW(0x7f931105c0) for (1184:system_server)
08-28 14:54:13.067  1184  1194 D WindowManager: addWindowToListInOrderLocked: win=Window{e03b8c1 u0 ua.meugen.android.popularmovies/ua.meugen.android.popularmovies.ui.activities.MoviesActivity} Callers=com.android.server.wm.WindowManagerService.addWindow:2740 com.android.server.wm.Session.addToDisplay:171 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:133 
08-28 14:54:13.069 11211 11211 V ActivityThread: Resuming ActivityRecord{da4f218 token=android.os.BinderProxy@78e9471 {ua.meugen.android.popularmovies/ua.meugen.android.popularmovies.ui.activities.MoviesActivity}} with isForward=true
08-28 14:54:13.069 11211 11211 V PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{c1a38e4 ua.meugen.android.popularmovies/ua.meugen.android.popularmovies.ui.activities.MoviesActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{a74bde2 V.E...... R.....ID 0,0-0,0}
08-28 14:54:13.069 11211 11211 V ActivityThread: Scheduling idle handler for ActivityRecord{da4f218 token=android.os.BinderProxy@78e9471 {ua.meugen.android.popularmovies/ua.meugen.android.popularmovies.ui.activities.MoviesActivity}}
08-28 14:54:13.070 11211 11211 D ActivityThreadInjector: clearCachedDrawables.
--------- beginning of crash
08-28 14:54:13.070 11211 11211 E AndroidRuntime: FATAL EXCEPTION: main
08-28 14:54:13.070 11211 11211 E AndroidRuntime: Process: ua.meugen.android.popularmovies, PID: 11211

**Comment by meugen** [comment]
Fixed. Thanks for notice this issue.
